from __future__ import annotations

import logging
import re
import shutil
from datetime import datetime
from pathlib import Path

import markdown

logger = logging.getLogger(__name__)

DATE_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}$")

STYLE_CSS = """\
:root {
  --bg: #f6f7fb;
  --card: #ffffff;
  --text: #1f2937;
  --muted: #6b7280;
  --accent: #2563eb;
  --border: #e5e7eb;
  --shadow: 0 10px 30px rgba(15, 23, 42, 0.08);
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  background: linear-gradient(180deg, #eef2ff 0%, var(--bg) 220px);
  color: var(--text);
  line-height: 1.7;
}

.container {
  max-width: 960px;
  margin: 0 auto;
  padding: 32px 20px 64px;
}

.site-header {
  margin-bottom: 24px;
}

.site-header h1 {
  margin: 0 0 8px;
  font-size: 2rem;
}

.site-header p {
  margin: 0;
  color: var(--muted);
}

.card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 16px;
  box-shadow: var(--shadow);
  padding: 28px;
  margin-bottom: 24px;
}

.card h2 {
  margin-top: 0;
  font-size: 1.35rem;
}

.archive-list {
  list-style: none;
  padding: 0;
  margin: 0;
  display: grid;
  gap: 10px;
}

.archive-list a {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 14px;
  border: 1px solid var(--border);
  border-radius: 10px;
  text-decoration: none;
  color: var(--text);
  background: #fafafa;
}

.archive-list a:hover {
  border-color: var(--accent);
  background: #eff6ff;
}

.archive-list .date {
  font-weight: 600;
}

.archive-list .link {
  color: var(--accent);
  font-size: 0.95rem;
}

.report-content h1 {
  margin-top: 0;
  font-size: 1.8rem;
}

.report-content h2 {
  margin-top: 2rem;
  padding-bottom: 0.4rem;
  border-bottom: 1px solid var(--border);
}

.report-content h3 {
  margin-top: 1.5rem;
}

.report-content ul {
  padding-left: 1.2rem;
}

.report-content a {
  color: var(--accent);
}

.report-content p,
.report-content li {
  color: #374151;
}

.back-link {
  display: inline-block;
  margin-bottom: 16px;
  color: var(--accent);
  text-decoration: none;
  font-weight: 600;
}

.back-link:hover {
  text-decoration: underline;
}

.site-footer {
  margin-top: 32px;
  color: var(--muted);
  font-size: 0.9rem;
  text-align: center;
}

@media (max-width: 640px) {
  .container {
    padding: 20px 14px 48px;
  }

  .card {
    padding: 20px;
  }

  .site-header h1 {
    font-size: 1.6rem;
  }
}
"""


def _parse_report_date(path: Path) -> str | None:
    stem = path.stem
    if DATE_PATTERN.match(stem):
        return stem
    return None


def _list_reports(output_dir: Path) -> list[tuple[str, Path]]:
    reports_dir = output_dir / "reports"
    if not reports_dir.exists():
        return []

    items: list[tuple[str, Path]] = []
    for path in reports_dir.glob("*.md"):
        report_date = _parse_report_date(path)
        if report_date:
            items.append((report_date, path))

    items.sort(key=lambda item: item[0], reverse=True)
    return items


def _md_to_html(md_text: str) -> str:
    return markdown.markdown(
        md_text,
        extensions=["extra", "sane_lists", "nl2br"],
    )


def _page_shell(
    title: str,
    body: str,
    *,
    back_link: str | None = None,
    asset_prefix: str = "assets",
) -> str:
    back_html = ""
    if back_link:
        back_html = f'<a class="back-link" href="{back_link}">← 返回首页</a>\n'

    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <link rel="stylesheet" href="{asset_prefix}/style.css">
</head>
<body>
  <div class="container">
    <header class="site-header">
      <h1>每日论文日报</h1>
      <p>自动抓取 arXiv 高质量论文，生成研究热点与重要事件摘要</p>
    </header>
    {back_html}
    {body}
    <footer class="site-footer">Generated by paper_reading · Updated automatically</footer>
  </div>
</body>
</html>
"""


def _write_css(site_dir: Path) -> None:
    assets_dir = site_dir / "assets"
    assets_dir.mkdir(parents=True, exist_ok=True)
    (assets_dir / "style.css").write_text(STYLE_CSS, encoding="utf-8")


def _write_report_pages(reports: list[tuple[str, Path]], site_dir: Path) -> None:
    reports_html_dir = site_dir / "reports"
    reports_html_dir.mkdir(parents=True, exist_ok=True)

    for report_date, md_path in reports:
        md_text = md_path.read_text(encoding="utf-8")
        content_html = _md_to_html(md_text)
        body = f'<main class="card report-content">{content_html}</main>'
        html = _page_shell(
            f"每日论文日报 {report_date}",
            body,
            back_link="../index.html",
            asset_prefix="../assets",
        )
        (reports_html_dir / f"{report_date}.html").write_text(html, encoding="utf-8")


def _write_index(reports: list[tuple[str, Path]], site_dir: Path) -> None:
    if not reports:
        body = '<main class="card"><p>暂无日报数据，请先运行抓取任务。</p></main>'
        (site_dir / "index.html").write_text(
            _page_shell("每日论文日报", body),
            encoding="utf-8",
        )
        return

    latest_date, latest_path = reports[0]
    latest_html = _md_to_html(latest_path.read_text(encoding="utf-8"))

    archive_items = []
    for report_date, _ in reports:
        archive_items.append(
            f'<li><a href="reports/{report_date}.html">'
            f'<span class="date">{report_date}</span>'
            f'<span class="link">查看详情 →</span>'
            f"</a></li>"
        )

    body = f"""
<main class="card report-content">
  <p><strong>最新更新：</strong>{latest_date}</p>
  {latest_html}
</main>
<section class="card">
  <h2>历史归档</h2>
  <ul class="archive-list">
    {''.join(archive_items)}
  </ul>
</section>
"""
    (site_dir / "index.html").write_text(
        _page_shell("每日论文日报", body),
        encoding="utf-8",
    )


def build_site(output_dir: Path, site_dir: Path) -> Path:
    reports = _list_reports(output_dir)

    if site_dir.exists():
        shutil.rmtree(site_dir)
    site_dir.mkdir(parents=True, exist_ok=True)

    _write_css(site_dir)
    _write_report_pages(reports, site_dir)
    _write_index(reports, site_dir)

    logger.info(
        "Site built at %s with %d report pages",
        site_dir,
        len(reports),
    )
    return site_dir
